/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class example_JniBridge */

#ifndef _Included_example_JniBridge
#define _Included_example_JniBridge
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     example_JniBridge
 * Method:    nativeCalculateSquares
 * Signature: ([J)[J
 */
JNIEXPORT jlongArray JNICALL Java_example_JniBridge_nativeCalculateSquares
  (JNIEnv *env, jobject obj, jlongArray values, jint numValues);

#ifdef __cplusplus
}
#endif
#endif
